name: Webhook on Main Branch

on:
  push:
    branches: [ main ]

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
